name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: dani03
        # Password or personal access token used to log against the Docker registry
        password: ${{secrets.DOCKERHUB_PASSWORD}}
        
    - name: PWD
      run: pwd
      
    - uses: actions/checkout@v3
    - name: LS
      run: ls
      
    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      uses: docker/build-push-action@v4.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: ./dockerfiles
        # Path to the Dockerfile
        file: php.dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
